### ISSUE TITLE
support for aot compilation with torch.export?

### ISSUE THREAD

**Issue by rbavery** [pytorch-labs/segment-anything-fast#68]
thanks for this amazing work and the accompanying blog post, very educational! 

would it be possible to export this fast sam variant with torch.export or tracing? I suspect the answer may be no because this torch.compile variation supports jagged arrays and torch.export doesn't, but thought I would check. 

In any case, any information on the ability to export this model for inference would be valuable!

I'd like to use this variation of SAM in torchserve, we currently experience long encode times for each image request. I noticed this comment in #67 which makes me wonder if the JIT compile times will be too long for a user to interactively use this variation of SAM since it will need to be compiled for each REST request.

> Please also note that the first time you're running this model you'll likely need to wait a bit for it to compile.

**Comment by cpuhrsch** [comment]
Thanks for opening this issue! Hm, I think you should be able to export the image encoder (`predictor.model.image_encoder`) since it can be compiled with CUDA graph support and max-autotune. I haven't tried this yet to be honest, but are happy to take a look if you run into any issues :) 

On the compile time issue: The image_encoder is always passed the same input size (at least in the context of SamPredictor) so it doesn't recompile after it compiled once. That means you shouldn't expect to see long compilation times if you're doing the same. You only need to compile it once. You can check this btw by setting the environment variable `TORCH_LOGS='recompiles'`

**Comment by guangy10** [comment]
> would it be possible to export this fast sam variant with torch.export or tracing? I suspect the answer may be no because this torch.compile variation supports jagged arrays and torch.export doesn't, but thought I would check.

Hi @rbavery Export using `torch.export()` API actually it works for both SAM Fast and the original SAM. #1202 shows various of input prompts we use to export and lower SAM to [ExecuTorch](https://github.com/pytorch/executorch). For SAM Fast, it exports successfully only with the boxes inputs so far. You can just take the export API and example inputs and try it out yourself. If you are interested in run SAM on-device eventually some day, we'd love to keep you updated about our work on ExecuTorch!

**Comment by rbavery** [comment]
thanks all for the info here, really helpful! I'll test out what the compile time is and give export a go.

I'm only working in the cloud and don't need to run SAM on-device currently, but much appreciate the advice @guangy10.
